language: python
python:
  - "3.6"
services:
  - postgresql
env:
  -DJANGO=2.1 DB=postgresql PILLOW=5.3
  - DJANGO=2.1 PILLOW=5.3
install:
  - pip install -r requirements.dev.txt
before_script:
  - psql -U postgres -c "\i bootstrap_db.sql"
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py collectstatic --noinput
script:
  - python manage.py test

deploy:
  provider: heroku
  buildpack: python
  app: 
    master: devpath-fw
  api_key:
    master: 388f7201-f9a1-4fae-95ab-368b804cf58f
  run:
    - "python manage.py migrate"
