language: python
python:
  - "3.6"
services:
  - postgresql
env:
  -DJANGO=2.1 DB=postgresql
install:
  - pip install -r requirements.dev.txt
before_script:
  - psql -U postgres -c "\i bootstrap_db.sql"
  - python manage.py makemigrations
  - python manage.py migrate
script:
  - python manage.py test