# Generated by Django 2.1.4 on 2018-12-06 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20181025_1559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
