# Generated by Django 2.1.2 on 2018-11-15 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('experience_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_type', to='dev_resume.EducationType')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ExperienceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ResumeEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('start', models.DateTimeField()),
                ('finish', models.DateTimeField()),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dev_resume.Education')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dev_resume.Resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('start', models.DateTimeField()),
                ('finish', models.DateTimeField()),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dev_resume.Experience')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dev_resume.Resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dev_resume.Resume')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_type', to='dev_resume.SkillType'),
        ),
        migrations.AddField(
            model_name='resumeskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dev_resume.Skill'),
        ),
        migrations.AddField(
            model_name='resume',
            name='experiences',
            field=models.ManyToManyField(blank=True, related_name='dev_experience', through='dev_resume.ResumeExperience', to='dev_resume.Experience'),
        ),
        migrations.AddField(
            model_name='resume',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dev_id', to='user_manager.Developer'),
        ),
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='dev_projects', to='dev_resume.Project'),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='dev_skills', through='dev_resume.ResumeSkill', to='dev_resume.Skill'),
        ),
        migrations.AddField(
            model_name='resume',
            name='studies',
            field=models.ManyToManyField(blank=True, related_name='dev_education', through='dev_resume.ResumeEducation', to='dev_resume.Education'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_type', to='dev_resume.ProjectType'),
        ),
        migrations.AddField(
            model_name='education',
            name='education_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_type', to='dev_resume.EducationType'),
        ),
        migrations.AlterUniqueTogether(
            name='resumeskill',
            unique_together={('resume', 'skill', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='resumeexperience',
            unique_together={('resume', 'experience', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='resumeeducation',
            unique_together={('resume', 'education', 'level')},
        ),
    ]
